title: "JQ Recipes"
description: snippets for working with jq
baseurl: "/jq-recipes"
url: "https://nntrn.github.io"
repository: nntrn/jq-recipes
favicon_ico: "/assets/favicon.ico"

markdown: kramdown

kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

github_username: nntrn

stylesheets:
  - styles/highlight.css
  - styles/main.css
  - styles/grid.css
  - styles/cheatsheet.css

defaults:
  - scope:
      path: "_functions/*.md"
      type: "functions"
    values:
      layout: minimal
  - scope:
      path: "_general/*.md"
      type: "general"
    values:
      layout: minimal
  - scope:
      path: "_notes/*.md"
      type: "notes"
    values:
      layout: minimal
  - scope:
      path: "_transform/*.md"
      type: "transform"
    values:
      layout: minimal
  - scope:
      path: "**/index.html"
    values:
      layout: cheatsheet

collections:
  general:
    output: true
  functions:
    output: true
  transform:
    output: true
  notes:
    output: true

sidebar: ["general", "transform", "functions", "notes"]

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  endings: all
  comments: ["<!--", "-->"]
  startings: []
  blanklines: true
  profile: false

sass:
  style: compressed

exclude:
  - readme.md
  - Gemfile.lock
  - scripts
