title: "JQ Recipes"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: custom
heading_anchors: true

markdown: kramdown

kramdown:
  toc_levels: 2..6

github_username: nntrn

aux_links:
  "Source Code":
    - "//github.com/nntrn/jq-recipes"

# collections:
#   docs:
#     permalink: /:slug

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      #       layout: "default"
      permalink: /:title/

exclude: [readme.md]

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  style: compact

compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: all
  blanklines: false
  profile: false
  startings: []
