title: "JQ Recipes"
description: snippets for working with jq
baseurl: "/jq-recipes"
url: "https://nntrn.github.io"
repository: nntrn/jq-recipes
favicon_ico: "/assets/favicon.ico"

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

github_username: nntrn

stylesheets:
  - styles/highlight.css

defaults:
  - scope:
      path: "_functions"
    values:
      layout: minimal
  - scope:
      path: "_general"
    values:
      layout: minimal

collections:
  general:
    output: true
  functions:
    output: true

sidebar: ["functions", "general"]

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  endings: all
  comments: ["<!--", "-->"]
  startings: []
  blanklines: true
  profile: false

exclude:
  - readme.md
  - Gemfile.lock
  - _config.old.yml
  - scripts
