title: "JQ Recipes"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: custom

plugins:
  - jekyll-feed
  - jekyll-remote-theme

markdown: kramdown

kramdown:
  toc_levels: 2..6

github_username: nntrn

# Aux links for the upper right navigation
aux_links:
  "Source Code":
    - "//github.com/nntrn/jq-recipes"

sass:
  style: compact

exclude: [readme.md]
